version: '3'
services:
  redis:
    build: 
      context: redis
      dockerfile: redis.Dockerfile
    volumes:
      - redis-data:/data

  bot:
    build: ./bot
    restart: unless-stopped
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    env_file:
      - .env
    volumes:
      - ./bot:/app
      # - ./schedule.yml:/app/schedule.yml
    depends_on:
      - redis

volumes:
  redis-data:
