version: '3'
services:
  redis:
    build: 
      context: redis
      dockerfile: redis.Dockerfile
    ports:
      - 6379:6379

  bot:
    build: ./bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./bot:/app
      - ./schedule.yml:/app/schedule.yml
    depends_on:
      - redis
