# This is a basic workflow to help you get started with Actions

name: IPTKPI Bot CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ release/ipt-kpi ]
  pull_request:
    branches: [ release/ipt-kpi ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux, ipt-kpi-runner]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: "Copying env files"
        run: |
          echo ${{secrets.BOT_TOKEN}} > ./.env

      - name: "Decrypting links files"
        run: |
           ansible-playbook -vv decrypt.yml 

      - name: "Building new images..."
        run: docker-compose -f docker-compose.yml build --force-rm
      
      - name: "Recreating services..."
        run: docker-compose -f docker-compose.yml up -d --remove-orphans 
        
      - name: "Removing unused images after build and recreate..."
        run: docker image prune -f

