# This is a basic workflow to help you get started with Actions

name: IPTKPI Bot CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ release/ipt-kpi ]
  pull_request:
    branches: [ release/ipt-kpi ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux, ipt-kpi-runner]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: "Copying env files"
        run: |
          echo "docker_auth_password = \"${{secrets.GITLAB_TOKEN}}\"" > ./nomad/vars.hcl

      - name: "Authorizing in registry"
        run: |
           docker login -u baltazar1697 -p ${{secrets.GITLAB_TOKEN}} registry.gitlab.com

      - name: "Decrypting links files"
        run: |
           ansible-playbook -vv decrypt.yml 

      - name: "Building new images..."
        run: docker build -t registry.gitlab.com/m11259/schedulebot:latest -f build/bot/Dockerfile .
      
      - name: "Pushing to repo..."
        run: docker push registry.gitlab.com/m11259/schedulebot:latest

      - name: "Recreating services..."
        run: nomad run -address=http://nmd.ipt-isef-techno.com -token=${{secrets.NOMAD_TOKEN}} -var-file="nomad/vars.hcl" nomad/schedulebot.hcl

